export type AppLanguageCode = 'en' | 'es' | 'it' | 'ru' | 'uk';

export const supportedLanguages: Array<{ code: AppLanguageCode; nativeName: string }> = [
  { code: 'it', nativeName: 'Italiano' },
  { code: 'en', nativeName: 'English' },
  { code: 'uk', nativeName: 'Українська' },
  { code: 'ru', nativeName: 'Русский' },
  { code: 'es', nativeName: 'Español' },
];

export const defaultLanguage: AppLanguageCode = 'it';

export const appCopy = {
  it: {
    archive: {
      emptyBody:
        'Rispondi alla domanda di oggi nella Home. Le risposte che salvi compariranno qui.',
      emptyTitle: 'Non hai ancora risposte',
      headerKicker: 'Archivio',
      headerText:
        'Qui trovi le risposte che hai salvato. Ogni riflessione diventa disponibile dopo 20 minuti.',
      headerTitle: 'Il tuo archivio privato',
      loading: 'Caricamento delle risposte salvate…',
      mapBadge: (count: number) => (count === 1 ? '1 risposta' : `${count} risposte`),
      mapDominant: 'Tema più frequente',
      mapDominantMany: (count: number) =>
        `Questo tema compare in ${count} risposte: è quello che hai esplorato più spesso.`,
      mapDominantOnce:
        'Per ora compare in una sola risposta. Continua a rispondere per scoprire quali temi tornano più spesso.',
      mapNext: 'Prossima riflessione',
      mapTitle: 'Il tuo percorso',
      nextMirrorEmpty: 'Tutte le riflessioni salvate sono disponibili. La prossima arriverà con una nuova risposta.',
      nextMirrorIn: (time: string) => `Sarà disponibile tra ${time}.`,
      opened: 'Disponibile',
      reflection: 'Riflessione',
      reflectionOpensIn: (time: string) => `La riflessione sarà disponibile tra ${time}.`,
      sealed: 'In attesa',
      statsAnswers: 'risposte',
      statsOpen: 'riflessioni disponibili',
      statsWaiting: 'in attesa',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Scuro',
      home: 'Home',
      light: 'Chiaro',
      mask: 'Tema',
      ready: 'Disponibile',
      theme: 'Aspetto',
      waiting: 'Non disponibile',
    },
    home: {
      answerPlaceholder: 'Scrivi qui la tua risposta…',
      cardKicker: 'Domanda di oggi',
      headerKicker: 'Riflessione quotidiana',
      headerText: 'Rispondi con sincerità. Dopo 20 minuti potrai rileggere la risposta insieme a una breve riflessione.',
      loading: 'Caricamento della domanda di oggi…',
      memoryBadge: 'aggiornato',
      memoryLatest: 'Ultimo tema esplorato',
      memoryReturn: 'Ogni risposta rende il tuo percorso più personale.',
      memoryTitle: 'I tuoi progressi',
      open: 'Da completare',
      promise: 'Una domanda al giorno, per conoscerti meglio.',
      ritualStep1: 'Rispondi alla domanda di oggi.',
      ritualStep2: 'La riflessione sarà disponibile dopo 20 minuti.',
      ritualStep3: 'Potrai rileggerla quando vuoi.',
      ritualTitle: 'Come funziona',
      remoteConnected: 'Il tuo archivio online è aggiornato.',
      remoteLoadError: 'Non è stato possibile caricare l’archivio online.',
      remoteSaveError: 'La risposta è salvata su questo dispositivo, ma non nell’archivio online.',
      reflectionWaiting: (time: string | null) =>
        `La riflessione sarà disponibile tra ${time ?? 'pochi minuti'}. Poi potrai rileggere la tua risposta con calma.`,
      save: 'Salva la risposta',
      savedPrivate: 'Risposta salvata nel tuo archivio privato.',
      savedShared: 'Risposta salvata e condivisa con la community usando solo le tue iniziali.',
      savedLocal: 'Risposta salvata su questo dispositivo.',
      sealed: 'Salvata',
      sealedTitle: 'Risposta salvata',
      shareGoogle: 'Accedi per condividere la risposta. La condivisione richiede il salvataggio online.',
      shareText:
        'La condivisione è facoltativa. Le altre persone vedranno solo le tue iniziali e potranno leggere la risposta solo dopo aver risposto alla stessa domanda.',
      shareTitle: 'Condividi con la community',
      shortHint: 'Non cercare la risposta perfetta: scrivi ciò che pensi, anche in poche parole.',
      signalOne: '1 domanda al giorno',
      signalTime: 'Riflessione in 20 min',
      traces: 'risposte',
      mirrors: 'riflessioni',
      yesterdayMirror: 'La tua riflessione',
    },
    paths: {
      featuredBody:
        'Esplora una domanda per volta, così puoi dedicare a ogni risposta il tempo che merita.',
      featuredKicker: 'Esperienza guidata',
      featuredTitle: 'Una domanda alla volta',
      headerKicker: 'Percorsi',
      headerText: 'I percorsi raggruppano le domande per tema: amore, paura, successo, solitudine e senso della vita.',
      headerTitle: 'Scegli un percorso',
      locked:
        'Questo percorso non è ancora disponibile. Arriverà in un prossimo aggiornamento.',
      moreQuestions: (count: number) =>
        count === 1 ? 'Resta un’altra domanda nel percorso.' : `Restano altre ${count} domande nel percorso.`,
      openQuestions: (count: number) => (count === 1 ? '1 domanda' : `${count} domande`),
      presto: 'In arrivo',
      questionIntro:
        'Queste sono alcune domande del percorso. Ogni giorno ne troverai una nella Home.',
      selected: 'Selezionato',
    },
    profile: {
      account: 'Account',
      accountLinked: 'Accesso effettuato',
      accountNotLinked: 'Non hai effettuato l’accesso',
      cloudMissing: 'Salvataggio online non disponibile',
      cloudMissingText: 'Le risposte saranno salvate solo su questo dispositivo.',
      firebase: 'Salvataggio online',
      googleLogin: 'Accesso con Google',
      appleLogin: 'Accesso con Apple',
      headerKicker: 'Profilo',
      headerText:
        'Gestisci il tuo account, la lingua, l’aspetto dell’app e le impostazioni sulla privacy.',
      headerTitle: 'Account e preferenze',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Segui il progetto per ricevere aggiornamenti e vedere i contenuti dietro le quinte.',
      language: 'Lingua',
      login: 'Entra con Google',
      loginOpening: 'Apertura Google…',
      logout: 'Esci',
      privacy: 'Privacy',
      privacyArchive: 'Archivio personale',
      privacyArchiveText:
        'Le risposte salvate restano nel tuo archivio. Se ne condividi una, la community riceve una copia separata.',
      privacyConsent: 'Condivisione reversibile',
      privacyConsentText: 'Puoi rendere di nuovo privata una risposta condivisa in qualsiasi momento dall’Archivio.',
      privacyInitials: 'Solo le tue iniziali',
      privacyInitialsText: 'Le risposte condivise non mostrano il tuo nome completo, l’email o il profilo di accesso.',
      signInText: 'Accedi per ritrovare il tuo archivio online e gestire le risposte condivise.',
      status: 'Disponibilità dei servizi',
      themeHelp: 'Scegli l’aspetto che trovi più facile da leggere.',
    },
    shared: {
      firebaseMissing: 'La condivisione non è disponibile al momento.',
      googlePrompt: 'Accedi per leggere le risposte di altre persone alla stessa domanda.',
      loadAnswersError:
        'Non è stato possibile caricare le risposte della community. Verifica di aver salvato questa risposta nel tuo account.',
      loadingAnswers: 'Caricamento delle risposte della community…',
      makePrivate: 'Rendi privata',
      noAnswers:
        'Non ci sono ancora altre risposte a questa domanda. Riprova più tardi.',
      openError: 'Non è stato possibile condividere la risposta. Riprova.',
      openStatus: 'Risposta condivisa con la community.',
      opening: 'Condivisione…',
      openWithInitials: 'Condividi con le iniziali',
      privateText:
        'Questa risposta è privata. Se la condividi, le altre persone vedranno solo le tue iniziali. Potrai anche leggere le risposte di chi ha ricevuto la stessa domanda.',
      privateError: 'Non è stato possibile rendere privata la risposta. Riprova.',
      privateStatus: 'La risposta ora è privata e resta solo nel tuo archivio.',
      acceptTermsBeforeLogin: 'Prima di continuare, accetta i termini e le regole della community.',
      blockAuthor: 'Blocca autore',
      blockError: 'Il blocco non è stato completato, ma la risposta è stata nascosta su questo dispositivo.',
      blockStatus: 'Autore bloccato. La risposta è stata nascosta e inviata alla moderazione.',
      filterBlocked:
        'Questa risposta potrebbe contenere dati di contatto o contenuti non consentiti e non può essere condivisa.',
      report: 'Segnala',
      reportError: 'La segnalazione non è stata inviata, ma la risposta è stata nascosta su questo dispositivo.',
      title: 'Risposte della community',
    },
  },
  en: {
    archive: {
      emptyBody: 'Answer today’s question on the Home screen. The answers you save will appear here.',
      emptyTitle: 'You have no answers yet',
      headerKicker: 'Archive',
      headerText: 'Find all your saved answers here. Each reflection becomes available after 20 minutes.',
      headerTitle: 'Your private archive',
      loading: 'Loading your saved answers…',
      mapBadge: (count: number) => (count === 1 ? '1 answer' : `${count} answers`),
      mapDominant: 'Most common theme',
      mapDominantMany: (count: number) =>
        `This theme appears in ${count} answers, making it the one you have explored most often.`,
      mapDominantOnce: 'It appears in one answer so far. Keep answering to discover which themes return most often.',
      mapNext: 'Next reflection',
      mapTitle: 'Your journey',
      nextMirrorEmpty: 'All your saved reflections are available. The next one will follow a new answer.',
      nextMirrorIn: (time: string) => `Available in ${time}.`,
      opened: 'Available',
      reflection: 'Reflection',
      reflectionOpensIn: (time: string) => `The reflection will be available in ${time}.`,
      sealed: 'Waiting',
      statsAnswers: 'answers',
      statsOpen: 'available reflections',
      statsWaiting: 'waiting',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Dark',
      home: 'Home',
      light: 'Light',
      mask: 'Theme',
      ready: 'Available',
      theme: 'Appearance',
      waiting: 'Unavailable',
    },
    home: {
      answerPlaceholder: 'Write your answer here…',
      cardKicker: 'Today’s question',
      headerKicker: 'Daily reflection',
      headerText: 'Answer honestly. After 20 minutes, you can reread your answer with a short reflection.',
      loading: 'Loading today’s question…',
      memoryBadge: 'updated',
      memoryLatest: 'Most recent theme',
      memoryReturn: 'Every answer makes your journey more personal.',
      memoryTitle: 'Your progress',
      open: 'Not answered',
      promise: 'One question a day, to help you understand yourself.',
      ritualStep1: 'Answer today’s question.',
      ritualStep2: 'Your reflection will be available after 20 minutes.',
      ritualStep3: 'You can reread it whenever you want.',
      ritualTitle: 'How it works',
      remoteConnected: 'Your online archive is up to date.',
      remoteLoadError: 'Your online archive could not be loaded.',
      remoteSaveError: 'Your answer is saved on this device, but not in your online archive.',
      reflectionWaiting: (time: string | null) =>
        `Your reflection will be available in ${time ?? 'a few minutes'}. Then you can reread your answer at your own pace.`,
      save: 'Save answer',
      savedPrivate: 'Answer saved in your private archive.',
      savedShared: 'Answer saved and shared with the community using only your initials.',
      savedLocal: 'Answer saved on this device.',
      sealed: 'Saved',
      sealedTitle: 'Answer saved',
      shareGoogle: 'Sign in to share your answer. Sharing requires online storage.',
      shareText:
        'Sharing is optional. Other people will see only your initials and can read your answer only after answering the same question.',
      shareTitle: 'Share with the community',
      shortHint: 'Do not look for the perfect answer. Write what you think, even in a few words.',
      signalOne: '1 question a day',
      signalTime: 'Reflection in 20 min',
      traces: 'answers',
      mirrors: 'reflections',
      yesterdayMirror: 'Your reflection',
    },
    paths: {
      featuredBody: 'Explore one question at a time, so you can give each answer the attention it deserves.',
      featuredKicker: 'Guided experience',
      featuredTitle: 'One question at a time',
      headerKicker: 'Paths',
      headerText: 'Paths group questions by theme: love, fear, success, solitude, and the meaning of life.',
      headerTitle: 'Choose a path',
      locked: 'This path is not available yet. It will arrive in a future update.',
      moreQuestions: (count: number) =>
        count === 1 ? '1 more question remains in this path.' : `${count} more questions remain in this path.`,
      openQuestions: (count: number) => (count === 1 ? '1 question' : `${count} questions`),
      presto: 'Coming soon',
      questionIntro:
        'These are some of the questions in this path. You will find one on the Home screen each day.',
      selected: 'Selected',
    },
    profile: {
      account: 'Account',
      accountLinked: 'Signed in',
      accountNotLinked: 'Not signed in',
      cloudMissing: 'Online storage unavailable',
      cloudMissingText: 'Your answers will be saved only on this device.',
      firebase: 'Online storage',
      googleLogin: 'Sign in with Google',
      appleLogin: 'Sign in with Apple',
      headerKicker: 'Profile',
      headerText: 'Manage your account, language, app appearance, and privacy settings.',
      headerTitle: 'Account and preferences',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Follow the project for updates and behind-the-scenes content.',
      language: 'Language',
      login: 'Sign in with Google',
      loginOpening: 'Opening Google…',
      logout: 'Sign out',
      privacy: 'Privacy',
      privacyArchive: 'Personal archive',
      privacyArchiveText: 'Saved answers remain in your archive. If you share one, the community receives a separate copy.',
      privacyConsent: 'Reversible sharing',
      privacyConsentText: 'You can make a shared answer private again at any time from the Archive.',
      privacyInitials: 'Only your initials',
      privacyInitialsText: 'Shared answers do not show your full name, email, or sign-in profile.',
      signInText: 'Sign in to access your online archive and manage shared answers.',
      status: 'Service availability',
      themeHelp: 'Choose the appearance that is easiest for you to read.',
    },
    shared: {
      firebaseMissing: 'Sharing is currently unavailable.',
      googlePrompt: 'Sign in to read other people’s answers to the same question.',
      loadAnswersError: 'Community answers could not be loaded. Make sure this answer is saved to your account.',
      loadingAnswers: 'Loading community answers…',
      makePrivate: 'Make private',
      noAnswers: 'There are no other answers to this question yet. Try again later.',
      openError: 'Your answer could not be shared. Try again.',
      openStatus: 'Answer shared with the community.',
      opening: 'Sharing…',
      openWithInitials: 'Share with your initials',
      privateText:
        'This answer is private. If you share it, other people will see only your initials. You will also be able to read answers from people who received the same question.',
      privateError: 'Your answer could not be made private. Try again.',
      privateStatus: 'Your answer is now private and remains only in your archive.',
      acceptTermsBeforeLogin: 'Accept the terms and community rules before continuing.',
      blockAuthor: 'Block author',
      blockError: 'The author could not be blocked, but the answer was hidden on this device.',
      blockStatus: 'Author blocked. The answer was hidden and sent to moderation.',
      filterBlocked:
        'This answer may contain contact details or content that is not allowed, so it cannot be shared.',
      report: 'Report',
      reportError: 'The report could not be sent, but the answer was hidden on this device.',
      title: 'Community answers',
    },
  },
  uk: {
    archive: {
      emptyBody: 'Дай відповідь на запитання дня на головній. Відтоді цей простір почне пам’ятати.',
      emptyTitle: 'Ще немає маски',
      headerKicker: 'Архів',
      headerText: 'Тут зберігаються твої відповіді. Кожен роздум стає доступним через 20 хвилин.',
      headerTitle: 'Твоя приватна пам’ять',
      loading: 'Шукаю збережені сліди…',
      mapBadge: (count: number) => (count === 1 ? '1 слід' : `${count} слідів`),
      mapDominant: 'Найчастіша маска',
      mapDominantMany: (count: number) =>
        `Вона з’являлася ${count} разів: можливо, це межа, якої ти торкаєшся найчастіше.`,
      mapDominantOnce:
        'Поки що вона з’явилася один раз. Ще кілька відповідей допоможуть побачити форму.',
      mapNext: 'Наступне дзеркало',
      mapTitle: 'Особиста мапа',
      nextMirrorEmpty: 'Усі збережені дзеркала відкриті. Наступне народиться із сьогоднішнього запитання.',
      nextMirrorIn: (time: string) => `Відкриється через ${time}.`,
      opened: 'Відкрита',
      reflection: 'Відображення',
      reflectionOpensIn: (time: string) => `Дзеркало відкриється через ${time}.`,
      sealed: 'Запечатана',
      statsAnswers: 'відповідей',
      statsOpen: 'відкритих дзеркал',
      statsWaiting: 'очікують',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Темна',
      home: 'Головна',
      light: 'Світла',
      mask: 'Маска',
      ready: 'Готово',
      theme: 'Вигляд',
      waiting: 'Потрібно підключити',
    },
    home: {
      answerPlaceholder: 'Зніми першу маску тут…',
      cardKicker: 'Запитання дня',
      headerKicker: 'Щоденний ритуал',
      headerText: 'Відповідай щиро. Через 20 хвилин ти зможеш перечитати відповідь разом із коротким роздумом.',
      loading: 'Відкриваю сьогоднішню печатку…',
      memoryBadge: 'триває',
      memoryLatest: 'Остання зустрінута маска',
      memoryReturn: 'Кожне повернення робить ритуал менш випадковим і більш твоїм.',
      memoryTitle: 'Нитка',
      open: 'Відкрита',
      promise: 'Одне запитання. Потім тиша.',
      ritualStep1: 'Одне запитання, вибране на сьогодні.',
      ritualStep2: 'Роздум стане доступним через 20 хвилин.',
      ritualStep3: 'Дзеркало, яке можна перечитати без поспіху.',
      ritualTitle: 'Ритуал',
      remoteConnected: 'Архів підключено до твого акаунта.',
      remoteLoadError: 'Не вдалося прочитати віддалений архів.',
      remoteSaveError: 'Відповідь збережено на цьому пристрої. Віддалене збереження не вдалося.',
      reflectionWaiting: (time: string | null) =>
        `Роздум стане доступним через ${time ?? 'кілька хвилин'}. Після цього ти зможеш спокійно перечитати свою відповідь.`,
      save: 'Запечатати відповідь',
      savedPrivate: 'Відповідь збережено у твоєму особистому просторі.',
      savedShared: 'Відповідь збережено й відкрито для спільної кімнати з твоїми ініціалами.',
      savedLocal: 'Відповідь збережено на цьому пристрої.',
      sealed: 'Запечатана',
      sealedTitle: 'Відповідь запечатана',
      shareGoogle: 'Щоб відкрити відповідь для спільної кімнати, потрібен вхід.',
      shareText:
        'Увімкни лише якщо хочеш: інші побачать тільки ініціали і лише після відповіді на те саме запитання.',
      shareTitle: 'Захищений обмін',
      shortHint: 'Не треба писати красиво. Треба писати чесно, навіть трохи.',
      signalOne: '1 запитання',
      signalTime: 'Роздум через 20 хв',
      traces: 'сліди',
      mirrors: 'дзеркала',
      yesterdayMirror: 'Твій роздум',
    },
    paths: {
      featuredBody: 'Обмеження тут не трюк: воно зменшує шум, підсилює повернення і дає відповіді простір.',
      featuredKicker: 'Керований досвід',
      featuredTitle: 'Одне запитання за раз',
      headerKicker: 'Шляхи',
      headerText: 'Кожна маска має ритм: любов, страх, амбіція, самотність, сенс.',
      headerTitle: 'Обери правильні двері',
      locked: 'Ця маска ще за дверима. Вона відкриється, коли в архіві буде достатньо слідів.',
      moreQuestions: (count: number) => `Ще ${count} запитань залишаються у шляху.`,
      openQuestions: (count: number) => `${count} запитань`,
      presto: 'Незабаром',
      questionIntro:
        'Запитання, які цей шлях тримає в щоденному ритуалі. Вони не приходять усі разом: очікування є частиною досвіду.',
      selected: 'В дослідженні',
    },
    profile: {
      account: 'Акаунт',
      accountLinked: 'Акаунт підключено',
      accountNotLinked: 'Не підключено',
      cloudMissing: 'Хмару не налаштовано',
      cloudMissingText: 'Відповіді залишаються на цьому пристрої, доки Firebase не буде підключено.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      appleLogin: 'Apple Login',
      headerKicker: 'Профіль',
      headerText: 'Акаунт, збереження і поширення розділені: обирай, що відкрити, а що залишити своїм.',
      headerTitle: 'Контроль, не оголення',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Стеж за проєктом поза щоденним ритуалом: оновлення, залаштунки та нові відкриття.',
      language: 'Мова',
      login: 'Увійти через Google',
      loginOpening: 'Відкриваю Google…',
      logout: 'Вийти',
      privacy: 'Приватність',
      privacyArchive: 'Особистий архів',
      privacyArchiveText: 'Збережені відповіді залишаються у твоєму просторі. Спільна кімната має окрему копію.',
      privacyConsent: 'Зворотна згода',
      privacyConsentText: 'Кожну спільну відповідь можна знову зробити приватною в Архіві.',
      privacyInitials: 'Лише ініціали',
      privacyInitialsText: 'Спільні голоси не показують повне ім’я, email або профіль входу.',
      signInText: 'Увійди, щоб повернути архів і керувати спільними відповідями.',
      status: 'Стан',
      themeHelp: 'Обери режим, який читається найкраще для тебе.',
    },
    shared: {
      firebaseMissing: 'Спільна кімната готова в коді. Вона відкриється, коли Firebase буде налаштовано.',
      googlePrompt: 'Увійди, щоб читати випадкові відповіді людей із тим самим запитанням.',
      loadAnswersError:
        'Інші голоси відкриваються лише тоді, коли ця відповідь збережена у твоєму акаунті.',
      loadingAnswers: 'Шукаю сумісні голоси…',
      makePrivate: 'Зробити приватною',
      noAnswers:
        'Поки що немає іншої відповіді. Ця кімната зростатиме, коли інші люди відповідатимуть на те саме запитання.',
      openError: 'Не вдалося відкрити цю відповідь для спільної кімнати.',
      openStatus: 'Відповідь відкрито для спільної кімнати.',
      opening: 'Відкриваю…',
      openWithInitials: 'Поділитися з ініціалами',
      privateText:
        'Ця відповідь приватна. Можна відкрити її для спільної кімнати лише з ініціалами, а потім читати голоси тих, хто відповів на те саме запитання.',
      privateError: 'Не вдалося зробити цю відповідь приватною.',
      privateStatus: 'Відповідь знову закрито. Вона залишається лише у твоєму особистому архіві.',
      acceptTermsBeforeLogin: 'Спочатку прийми умови та правила спільноти.',
      blockAuthor: 'Заблокувати автора',
      blockError: 'Блокування не дійшло до сервера. Я все одно приховав цей голос тут.',
      blockStatus: 'Автора заблоковано. Цей голос приховано й передано на модерацію.',
      filterBlocked:
        'Ця відповідь містить контактні дані або заборонений вміст і не може бути поширена.',
      report: 'Поскаржитися',
      reportError: 'Скарга не надійшла. Я все одно приховав цей голос тут.',
      title: 'Голоси інших',
    },
  },
  ru: {
    archive: {
      emptyBody: 'Ответь на вопрос дня на главной. С этого момента это пространство начнёт помнить.',
      emptyTitle: 'Пока нет маски',
      headerKicker: 'Архив',
      headerText: 'Здесь хранятся твои ответы. Каждое размышление становится доступным через 20 минут.',
      headerTitle: 'Твоя личная память',
      loading: 'Ищу сохранённые следы…',
      mapBadge: (count: number) => (count === 1 ? '1 след' : `${count} следов`),
      mapDominant: 'Самая частая маска',
      mapDominantMany: (count: number) =>
        `Она появлялась ${count} раз: возможно, это порог, которого ты касаешься чаще всего.`,
      mapDominantOnce:
        'Пока она появилась один раз. Ещё несколько ответов помогут увидеть форму.',
      mapNext: 'Следующее зеркало',
      mapTitle: 'Личная карта',
      nextMirrorEmpty: 'Все сохранённые зеркала открыты. Следующее начнётся с сегодняшнего вопроса.',
      nextMirrorIn: (time: string) => `Откроется через ${time}.`,
      opened: 'Открыта',
      reflection: 'Отражение',
      reflectionOpensIn: (time: string) => `Зеркало откроется через ${time}.`,
      sealed: 'Запечатана',
      statsAnswers: 'ответов',
      statsOpen: 'открытых зеркал',
      statsWaiting: 'в ожидании',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Тёмная',
      home: 'Главная',
      light: 'Светлая',
      mask: 'Маска',
      ready: 'Готово',
      theme: 'Вид',
      waiting: 'Подключить',
    },
    home: {
      answerPlaceholder: 'Сними первую маску здесь…',
      cardKicker: 'Вопрос дня',
      headerKicker: 'Ежедневный ритуал',
      headerText: 'Отвечай честно. Через 20 минут ты сможешь перечитать ответ вместе с коротким размышлением.',
      loading: 'Открываю сегодняшнюю печать…',
      memoryBadge: 'в процессе',
      memoryLatest: 'Последняя встреченная маска',
      memoryReturn: 'Каждое возвращение делает ритуал менее случайным и более твоим.',
      memoryTitle: 'Нить',
      open: 'Открыта',
      promise: 'Один вопрос. Потом тишина.',
      ritualStep1: 'Один вопрос, выбранный на сегодня.',
      ritualStep2: 'Размышление станет доступным через 20 минут.',
      ritualStep3: 'Зеркало, которое можно перечитать без спешки.',
      ritualTitle: 'Ритуал',
      remoteConnected: 'Архив подключён к твоему аккаунту.',
      remoteLoadError: 'Не удалось прочитать удалённый архив.',
      remoteSaveError: 'Ответ сохранён на этом устройстве. Удалённое сохранение не удалось.',
      reflectionWaiting: (time: string | null) =>
        `Размышление станет доступным через ${time ?? 'несколько минут'}. После этого ты сможешь спокойно перечитать свой ответ.`,
      save: 'Запечатать ответ',
      savedPrivate: 'Ответ сохранён в твоём личном пространстве.',
      savedShared: 'Ответ сохранён и открыт для общей комнаты с твоими инициалами.',
      savedLocal: 'Ответ сохранён на этом устройстве.',
      sealed: 'Запечатана',
      sealedTitle: 'Ответ запечатан',
      shareGoogle: 'Чтобы открыть ответ для общей комнаты, нужен вход.',
      shareText:
        'Включай только если хочешь: другие увидят только инициалы и только после ответа на тот же вопрос.',
      shareTitle: 'Защищённый обмен',
      shortHint: 'Не нужно писать красиво. Нужно писать честно, даже немного.',
      signalOne: '1 вопрос',
      signalTime: 'Размышление через 20 мин',
      traces: 'следы',
      mirrors: 'зеркала',
      yesterdayMirror: 'Твоё размышление',
    },
    paths: {
      featuredBody: 'Ограничение здесь не трюк: оно снижает шум, усиливает возвращение и даёт ответу место.',
      featuredKicker: 'Направленный опыт',
      featuredTitle: 'Один вопрос за раз',
      headerKicker: 'Пути',
      headerText: 'У каждой маски свой ритм: любовь, страх, амбиция, одиночество, смысл.',
      headerTitle: 'Выбери правильную дверь',
      locked: 'Эта маска пока за дверью. Она откроется, когда в архиве будет достаточно следов.',
      moreQuestions: (count: number) => `Ещё ${count} вопросов остаются в пути.`,
      openQuestions: (count: number) => `${count} вопросов`,
      presto: 'Скоро',
      questionIntro:
        'Вопросы, которые этот путь хранит в ежедневном ритуале. Они не приходят все сразу: ожидание — часть опыта.',
      selected: 'В исследовании',
    },
    profile: {
      account: 'Аккаунт',
      accountLinked: 'Аккаунт подключён',
      accountNotLinked: 'Не подключено',
      cloudMissing: 'Облако не настроено',
      cloudMissingText: 'Ответы остаются на этом устройстве, пока Firebase не подключён.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      appleLogin: 'Apple Login',
      headerKicker: 'Профиль',
      headerText: 'Аккаунт, сохранение и обмен разделены: выбирай, что открыть, а что оставить своим.',
      headerTitle: 'Контроль, не раскрытие',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Следи за проектом вне ежедневного ритуала: обновления, закулисье и новые открытия.',
      language: 'Язык',
      login: 'Войти через Google',
      loginOpening: 'Открываю Google…',
      logout: 'Выйти',
      privacy: 'Приватность',
      privacyArchive: 'Личный архив',
      privacyArchiveText: 'Сохранённые ответы остаются в твоём пространстве. Общая комната использует отдельную копию.',
      privacyConsent: 'Обратимое согласие',
      privacyConsentText: 'Любой общий ответ можно снова сделать приватным в Архиве.',
      privacyInitials: 'Только инициалы',
      privacyInitialsText: 'Общие голоса не показывают полное имя, email или профиль входа.',
      signInText: 'Войди, чтобы вернуть архив и управлять общими ответами.',
      status: 'Статус',
      themeHelp: 'Выбери режим, который читается лучше всего.',
    },
    shared: {
      firebaseMissing: 'Общая комната готова в коде. Она откроется, когда Firebase будет настроен.',
      googlePrompt: 'Войди, чтобы читать случайные ответы людей с тем же вопросом.',
      loadAnswersError: 'Другие голоса открываются только когда этот ответ сохранён в твоём аккаунте.',
      loadingAnswers: 'Ищу совместимые голоса…',
      makePrivate: 'Сделать приватным',
      noAnswers:
        'Пока нет другого ответа. Эта комната будет расти, когда другие люди ответят на тот же вопрос.',
      openError: 'Не удалось открыть этот ответ для общей комнаты.',
      openStatus: 'Ответ открыт для общей комнаты.',
      opening: 'Открываю…',
      openWithInitials: 'Поделиться с инициалами',
      privateText:
        'Этот ответ приватный. Можно открыть его для общей комнаты только с инициалами, а затем читать голоса тех, кто ответил на тот же вопрос.',
      privateError: 'Не удалось сделать этот ответ приватным.',
      privateStatus: 'Ответ снова закрыт. Он остаётся только в твоём личном архиве.',
      acceptTermsBeforeLogin: 'Сначала прими условия и правила сообщества.',
      blockAuthor: 'Заблокировать автора',
      blockError: 'Блокировка не дошла до сервера. Я всё равно скрыл этот голос здесь.',
      blockStatus: 'Автор заблокирован. Этот голос скрыт и отправлен на модерацию.',
      filterBlocked:
        'Этот ответ содержит контактные данные или запрещённый контент и не может быть опубликован.',
      report: 'Пожаловаться',
      reportError: 'Жалоба не отправилась. Я всё равно скрыл этот голос здесь.',
      title: 'Голоса других',
    },
  },
  es: {
    archive: {
      emptyBody: 'Responde a la pregunta del día en Inicio. Desde ahí, este espacio empezará a recordar.',
      emptyTitle: 'Aún no hay máscara',
      headerKicker: 'Archivo',
      headerText: 'Aquí se guardan tus respuestas. Cada reflexión está disponible después de 20 minutos.',
      headerTitle: 'Tu memoria privada',
      loading: 'Buscando las huellas guardadas…',
      mapBadge: (count: number) => (count === 1 ? '1 huella' : `${count} huellas`),
      mapDominant: 'Máscara más presente',
      mapDominantMany: (count: number) =>
        `Apareció ${count} veces: podría ser el umbral que más estás rozando.`,
      mapDominantOnce:
        'Por ahora apareció una vez. Hace falta alguna respuesta más para ver una forma.',
      mapNext: 'Próximo espejo',
      mapTitle: 'Mapa personal',
      nextMirrorEmpty: 'Todos los espejos guardados están abiertos. El próximo nace de la pregunta de hoy.',
      nextMirrorIn: (time: string) => `Se abre en ${time}.`,
      opened: 'Abierta',
      reflection: 'Reflexión',
      reflectionOpensIn: (time: string) => `El espejo se abre en ${time}.`,
      sealed: 'Sellada',
      statsAnswers: 'respuestas',
      statsOpen: 'espejos abiertos',
      statsWaiting: 'en espera',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Oscuro',
      home: 'Inicio',
      light: 'Claro',
      mask: 'Máscara',
      ready: 'Listo',
      theme: 'Apariencia',
      waiting: 'Por conectar',
    },
    home: {
      answerPlaceholder: 'Quita la primera máscara aquí…',
      cardKicker: 'Pregunta de hoy',
      headerKicker: 'Ritual diario',
      headerText: 'Responde con sinceridad. Después de 20 minutos podrás releer tu respuesta con una breve reflexión.',
      loading: 'Abriendo el sello de hoy…',
      memoryBadge: 'en curso',
      memoryLatest: 'Última máscara encontrada',
      memoryReturn: 'Cada regreso hace que el ritual sea menos casual y más tuyo.',
      memoryTitle: 'El hilo',
      open: 'Abierta',
      promise: 'Una pregunta. Luego silencio.',
      ritualStep1: 'Una sola pregunta, elegida para hoy.',
      ritualStep2: 'La reflexión estará disponible después de 20 minutos.',
      ritualStep3: 'Un espejo para releer sin prisa.',
      ritualTitle: 'El ritual',
      remoteConnected: 'Archivo conectado a tu cuenta.',
      remoteLoadError: 'No pude leer el archivo remoto.',
      remoteSaveError: 'Respuesta guardada en este dispositivo. El guardado remoto no funcionó.',
      reflectionWaiting: (time: string | null) =>
        `La reflexión estará disponible en ${time ?? 'unos minutos'}. Después podrás releer tu respuesta con calma.`,
      save: 'Sellar la respuesta',
      savedPrivate: 'Respuesta guardada en tu espacio personal.',
      savedShared: 'Respuesta guardada y abierta a la sala compartida con tus iniciales.',
      savedLocal: 'Respuesta guardada en este dispositivo.',
      sealed: 'Sellada',
      sealedTitle: 'Respuesta sellada',
      shareGoogle: 'Para abrir esta respuesta a la sala compartida hace falta acceder.',
      shareText:
        'Actívalo solo si quieres: los demás verán solo iniciales y solo después de responder a la misma pregunta.',
      shareTitle: 'Compartir protegido',
      shortHint: 'No hace falta escribir bien. Hace falta escribir de verdad, aunque sea poco.',
      signalOne: '1 pregunta',
      signalTime: 'Reflexión en 20 min',
      traces: 'huellas',
      mirrors: 'espejos',
      yesterdayMirror: 'Tu reflexión',
    },
    paths: {
      featuredBody: 'La escasez aquí no es truco: reduce ruido, aumenta el regreso y deja espacio a la respuesta.',
      featuredKicker: 'Experiencia guiada',
      featuredTitle: 'Una pregunta a la vez',
      headerKicker: 'Recorridos',
      headerText: 'Cada máscara tiene un ritmo: amor, miedo, ambición, soledad, sentido.',
      headerTitle: 'Elige la puerta correcta',
      locked: 'Esta máscara todavía está detrás de la puerta. Se abrirá cuando tu archivo tenga suficientes huellas.',
      moreQuestions: (count: number) => `Quedan ${count} preguntas más en el recorrido.`,
      openQuestions: (count: number) => `${count} preguntas`,
      presto: 'Pronto',
      questionIntro:
        'Preguntas que este recorrido guarda en el ritual diario. No llegan todas juntas: la espera es parte de la experiencia.',
      selected: 'En exploración',
    },
    profile: {
      account: 'Cuenta',
      accountLinked: 'Cuenta conectada',
      accountNotLinked: 'No conectado',
      cloudMissing: 'Cloud no configurado',
      cloudMissingText: 'Las respuestas quedan en este dispositivo hasta que Firebase esté conectado.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      appleLogin: 'Apple Login',
      headerKicker: 'Perfil',
      headerText: 'Cuenta, guardado y compartir quedan separados: eliges qué abrir y qué conservar tuyo.',
      headerTitle: 'Control, no exposición',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Sigue el proyecto fuera del ritual diario: novedades, detrás de escena y nuevas aperturas.',
      language: 'Idioma',
      login: 'Entrar con Google',
      loginOpening: 'Abriendo Google…',
      logout: 'Salir',
      privacy: 'Privacidad',
      privacyArchive: 'Archivo personal',
      privacyArchiveText: 'Las respuestas guardadas quedan en tu espacio. La sala compartida usa una copia separada.',
      privacyConsent: 'Consentimiento reversible',
      privacyConsentText: 'Cada respuesta compartida puede volver a ser privada desde el Archivo.',
      privacyInitials: 'Solo iniciales',
      privacyInitialsText: 'Las voces compartidas no muestran nombre completo, email ni perfil de acceso.',
      signInText: 'Entra para recuperar tu archivo y gestionar las respuestas compartidas.',
      status: 'Estado',
      themeHelp: 'Elige el modo que te resulte más legible.',
    },
    shared: {
      firebaseMissing: 'La sala compartida está lista en el código. Se abrirá cuando Firebase esté configurado.',
      googlePrompt: 'Entra para leer respuestas aleatorias de quien encontró la misma pregunta.',
      loadAnswersError: 'Las otras voces se abren solo cuando esta respuesta está guardada en tu cuenta.',
      loadingAnswers: 'Buscando voces compatibles…',
      makePrivate: 'Hacer privada',
      noAnswers:
        'Todavía no hay otra respuesta. Esta sala crecerá cuando otras personas respondan a la misma pregunta.',
      openError: 'No pude abrir esta respuesta a la sala compartida.',
      openStatus: 'Respuesta abierta a la sala compartida.',
      opening: 'Abriendo…',
      openWithInitials: 'Compartir con iniciales',
      privateText:
        'Esta respuesta es privada. Puedes abrirla a la sala compartida solo con iniciales y luego leer voces de quien respondió a la misma pregunta.',
      privateError: 'No pude hacer privada esta respuesta.',
      privateStatus: 'Respuesta cerrada de nuevo. Queda solo en tu archivo personal.',
      acceptTermsBeforeLogin: 'Acepta primero los términos y reglas de comunidad.',
      blockAuthor: 'Bloquear autor',
      blockError: 'El bloqueo no llegó al servidor. De todos modos oculté esta voz aquí.',
      blockStatus: 'Autor bloqueado. Esta voz se ocultó y se envió a moderación.',
      filterBlocked:
        'Esta respuesta contiene datos de contacto o contenido no permitido y no puede compartirse.',
      report: 'Denunciar',
      reportError: 'La denuncia no llegó. De todos modos oculté esta voz aquí.',
      title: 'Voces de otros',
    },
  },
} as const;

export type AppCopy = (typeof appCopy)[AppLanguageCode];
