export type AppLanguageCode = 'en' | 'es' | 'it' | 'ru' | 'uk';

export const supportedLanguages: Array<{ code: AppLanguageCode; nativeName: string }> = [
  { code: 'it', nativeName: 'Italiano' },
  { code: 'en', nativeName: 'English' },
  { code: 'uk', nativeName: 'Українська' },
  { code: 'ru', nativeName: 'Русский' },
  { code: 'es', nativeName: 'Español' },
];

export const defaultLanguage: AppLanguageCode = 'it';

export const appCopy = {
  it: {
    archive: {
      emptyBody:
        'Rispondi alla domanda del giorno nella Home. Da quel momento questo spazio inizierà a ricordare.',
      emptyTitle: 'Ancora nessuna maschera',
      headerKicker: 'Archivio',
      headerText:
        'Le risposte restano tue. Gli specchi si aprono quando il tempo ha fatto il suo lavoro.',
      headerTitle: 'La tua memoria privata',
      loading: 'Sto cercando le tracce salvate…',
      mapBadge: (count: number) => (count === 1 ? '1 traccia' : `${count} tracce`),
      mapDominant: 'Maschera più presente',
      mapDominantMany: (count: number) =>
        `È apparsa ${count} volte: potrebbe essere la soglia che stai sfiorando più spesso.`,
      mapDominantOnce:
        'Per ora è apparsa una volta. Serve ancora qualche risposta per vedere una forma.',
      mapNext: 'Prossimo specchio',
      mapTitle: 'Mappa personale',
      nextMirrorEmpty: 'Tutti gli specchi salvati sono aperti. Il prossimo nasce dalla domanda di oggi.',
      nextMirrorIn: (time: string) => `Si apre tra ${time}.`,
      opened: 'Aperta',
      reflection: 'Riflessione',
      reflectionOpensIn: (time: string) => `Lo specchio si apre tra ${time}.`,
      sealed: 'Sigillata',
      statsAnswers: 'risposte',
      statsOpen: 'specchi aperti',
      statsWaiting: 'in attesa',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Scuro',
      home: 'Home',
      light: 'Chiaro',
      mask: 'Maschera',
      ready: 'Pronto',
      theme: 'Aspetto',
      waiting: 'Da collegare',
    },
    home: {
      answerPlaceholder: 'Togli la prima maschera qui…',
      cardKicker: 'Domanda di oggi',
      headerKicker: 'Rito quotidiano',
      headerText: 'Scrivi senza recitare. Domani la risposta torna con uno specchio più gentile.',
      loading: 'Sto riaprendo il sigillo di oggi…',
      memoryBadge: 'in corso',
      memoryLatest: 'Ultima maschera incontrata',
      memoryReturn: 'Ogni ritorno rende il rito meno casuale e più tuo.',
      memoryTitle: 'Il filo',
      open: 'Aperta',
      promise: 'Una domanda. Poi silenzio.',
      ritualStep1: 'Una sola domanda, scelta per oggi.',
      ritualStep2: 'Ventiquattro ore di distanza.',
      ritualStep3: 'Uno specchio da rileggere senza fretta.',
      ritualTitle: 'Il rito',
      remoteConnected: 'Archivio collegato al tuo account Google.',
      remoteLoadError: 'Non sono riuscito a leggere l’archivio remoto.',
      remoteSaveError: 'Risposta salvata su questo dispositivo. Il salvataggio remoto non è riuscito.',
      reflectionWaiting: (time: string | null) =>
        `La riflessione si apre tra ${time ?? 'poco'}. Questo ritardo è parte del rituale: lascia alla risposta il tempo di cambiare temperatura.`,
      save: 'Sigilla la risposta',
      savedPrivate: 'Risposta salvata nel tuo spazio personale.',
      savedShared: 'Risposta salvata e aperta alla stanza condivisa con le tue iniziali.',
      savedLocal: 'Risposta salvata su questo dispositivo.',
      sealed: 'Sigillata',
      sealedTitle: 'Risposta sigillata',
      shareGoogle: 'Per aprire questa risposta alla stanza condivisa serve l’accesso Google.',
      shareText:
        'Attivala solo se vuoi: gli altri vedranno solo le iniziali e soltanto dopo aver risposto alla stessa domanda.',
      shareTitle: 'Condivisione protetta',
      shortHint: 'Non serve scrivere bene. Serve scrivere vero, anche poco.',
      signalOne: '1 domanda',
      signalTime: '24 ore',
      traces: 'tracce',
      mirrors: 'specchi',
      yesterdayMirror: 'Lo specchio di ieri',
    },
    paths: {
      featuredBody:
        'La scarsità qui non è trucco: riduce rumore, aumenta ritorno e lascia spazio alla risposta.',
      featuredKicker: 'Esperienza guidata',
      featuredTitle: 'Una domanda alla volta',
      headerKicker: 'Percorsi',
      headerText: 'Ogni maschera ha un ritmo: amore, paura, ambizione, solitudine, senso.',
      headerTitle: 'Scegli la porta giusta',
      locked:
        'Questa maschera resta ancora dietro la porta. Si aprirà quando il tuo archivio avrà abbastanza tracce da sostenerla.',
      moreQuestions: (count: number) => `Altre ${count} domande restano nel percorso.`,
      openQuestions: (count: number) => `${count} domande`,
      presto: 'Presto',
      questionIntro:
        'Domande che questo percorso custodisce nel rito quotidiano. Non arrivano tutte insieme: l’attesa fa parte dell’esperienza.',
      selected: 'In esplorazione',
    },
    profile: {
      account: 'Account',
      accountLinked: 'Collegato a Google',
      accountNotLinked: 'Non collegato',
      cloudMissing: 'Cloud non configurato',
      cloudMissingText: 'Le risposte restano su questo dispositivo finché Firebase non viene collegato.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      headerKicker: 'Profilo',
      headerText:
        'Account, salvataggio e condivisione restano separati: scegli cosa aprire e cosa tenere tuo.',
      headerTitle: 'Controllo, non esposizione',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Segui il progetto fuori dal rito quotidiano: aggiornamenti, dietro le quinte e nuove aperture.',
      language: 'Lingua',
      login: 'Entra con Google',
      loginOpening: 'Apertura Google…',
      logout: 'Esci',
      privacy: 'Privacy',
      privacyArchive: 'Archivio personale',
      privacyArchiveText:
        'Le risposte salvate restano nel tuo spazio. La stanza condivisa usa una copia separata.',
      privacyConsent: 'Consenso reversibile',
      privacyConsentText: 'Ogni risposta condivisa può tornare privata dall’Archivio.',
      privacyInitials: 'Iniziali soltanto',
      privacyInitialsText: 'Le voci condivise non mostrano nome completo, email o profilo Google.',
      signInText: 'Entra per ritrovare il tuo archivio e gestire le risposte condivise.',
      status: 'Stato',
      themeHelp: 'Scegli la modalità più leggibile per te.',
    },
    shared: {
      firebaseMissing: 'La stanza condivisa è pronta nel codice. Si aprirà quando Firebase sarà configurato.',
      googlePrompt: 'Entra con Google per leggere risposte casuali di chi ha incontrato la stessa domanda.',
      loadAnswersError:
        'Le altre voci si aprono solo quando questa risposta è salvata nel tuo account.',
      loadingAnswers: 'Sto cercando voci compatibili…',
      makePrivate: 'Rendi privata',
      noAnswers:
        'Nessun’altra risposta trovata per ora. Questa stanza crescerà quando altre persone risponderanno alla stessa domanda.',
      openError: 'Non sono riuscito ad aprire questa risposta alla stanza condivisa.',
      openStatus: 'Risposta aperta alla stanza condivisa.',
      opening: 'Apertura…',
      openWithInitials: 'Condividi con iniziali',
      privateText:
        'Questa risposta è privata. Puoi aprirla alla stanza condivisa con le sole iniziali, poi leggere le voci di chi ha risposto alla stessa domanda.',
      privateError: 'Non sono riuscito a rendere privata questa risposta.',
      privateStatus: 'Risposta richiusa. Resta solo nel tuo archivio personale.',
      report: 'Segnala',
      reportError: 'La segnalazione non è arrivata. Ho comunque nascosto questa voce qui.',
      title: 'Voci dagli altri',
    },
  },
  en: {
    archive: {
      emptyBody: 'Answer today’s question on Home. From there, this space will begin to remember.',
      emptyTitle: 'No mask yet',
      headerKicker: 'Archive',
      headerText: 'Your answers stay yours. Mirrors open when time has done its work.',
      headerTitle: 'Your private memory',
      loading: 'Looking for saved traces…',
      mapBadge: (count: number) => (count === 1 ? '1 trace' : `${count} traces`),
      mapDominant: 'Most present mask',
      mapDominantMany: (count: number) =>
        `It has appeared ${count} times: it may be the threshold you are touching most often.`,
      mapDominantOnce: 'For now it has appeared once. A few more answers will help a shape emerge.',
      mapNext: 'Next mirror',
      mapTitle: 'Personal map',
      nextMirrorEmpty: 'All saved mirrors are open. The next one begins with today’s question.',
      nextMirrorIn: (time: string) => `Opens in ${time}.`,
      opened: 'Open',
      reflection: 'Reflection',
      reflectionOpensIn: (time: string) => `The mirror opens in ${time}.`,
      sealed: 'Sealed',
      statsAnswers: 'answers',
      statsOpen: 'open mirrors',
      statsWaiting: 'waiting',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Dark',
      home: 'Home',
      light: 'Light',
      mask: 'Mask',
      ready: 'Ready',
      theme: 'Appearance',
      waiting: 'To connect',
    },
    home: {
      answerPlaceholder: 'Remove the first mask here…',
      cardKicker: 'Today’s question',
      headerKicker: 'Daily ritual',
      headerText: 'Write without performing. Tomorrow your answer returns as a kinder mirror.',
      loading: 'Opening today’s seal…',
      memoryBadge: 'active',
      memoryLatest: 'Last mask met',
      memoryReturn: 'Every return makes the ritual less random and more yours.',
      memoryTitle: 'The thread',
      open: 'Open',
      promise: 'One question. Then silence.',
      ritualStep1: 'One question, chosen for today.',
      ritualStep2: 'Twenty-four hours of distance.',
      ritualStep3: 'A mirror to reread without hurry.',
      ritualTitle: 'The ritual',
      remoteConnected: 'Archive connected to your Google account.',
      remoteLoadError: 'I could not read the remote archive.',
      remoteSaveError: 'Answer saved on this device. Remote saving did not work.',
      reflectionWaiting: (time: string | null) =>
        `The reflection opens in ${time ?? 'a little while'}. This delay is part of the ritual: it gives the answer time to change temperature.`,
      save: 'Seal the answer',
      savedPrivate: 'Answer saved in your personal space.',
      savedShared: 'Answer saved and opened to the shared room with your initials.',
      savedLocal: 'Answer saved on this device.',
      sealed: 'Sealed',
      sealedTitle: 'Answer sealed',
      shareGoogle: 'Google sign-in is required to open this answer to the shared room.',
      shareText:
        'Turn it on only if you want: others will see initials only, and only after answering the same question.',
      shareTitle: 'Protected sharing',
      shortHint: 'You do not need to write well. You need to write truthfully, even a little.',
      signalOne: '1 question',
      signalTime: '24 hours',
      traces: 'traces',
      mirrors: 'mirrors',
      yesterdayMirror: 'Yesterday’s mirror',
    },
    paths: {
      featuredBody: 'Scarcity is not a trick here: it lowers noise, increases return, and gives the answer space.',
      featuredKicker: 'Guided experience',
      featuredTitle: 'One question at a time',
      headerKicker: 'Paths',
      headerText: 'Every mask has a rhythm: love, fear, ambition, solitude, meaning.',
      headerTitle: 'Choose the right door',
      locked: 'This mask is still behind the door. It will open when your archive has enough traces to hold it.',
      moreQuestions: (count: number) => `${count} more questions remain in the path.`,
      openQuestions: (count: number) => `${count} questions`,
      presto: 'Soon',
      questionIntro:
        'Questions this path keeps inside the daily ritual. They do not arrive all at once: waiting is part of the experience.',
      selected: 'Exploring',
    },
    profile: {
      account: 'Account',
      accountLinked: 'Connected to Google',
      accountNotLinked: 'Not connected',
      cloudMissing: 'Cloud not configured',
      cloudMissingText: 'Answers stay on this device until Firebase is connected.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      headerKicker: 'Profile',
      headerText: 'Account, saving, and sharing stay separate: choose what to open and what to keep yours.',
      headerTitle: 'Control, not exposure',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Follow the project outside the daily ritual: updates, behind the scenes, and new openings.',
      language: 'Language',
      login: 'Sign in with Google',
      loginOpening: 'Opening Google…',
      logout: 'Sign out',
      privacy: 'Privacy',
      privacyArchive: 'Personal archive',
      privacyArchiveText: 'Saved answers stay in your space. The shared room uses a separate copy.',
      privacyConsent: 'Reversible consent',
      privacyConsentText: 'Every shared answer can become private again from the Archive.',
      privacyInitials: 'Initials only',
      privacyInitialsText: 'Shared voices do not show full name, email, or Google profile.',
      signInText: 'Sign in to recover your archive and manage shared answers.',
      status: 'Status',
      themeHelp: 'Choose the mode that feels most readable to you.',
    },
    shared: {
      firebaseMissing: 'The shared room is ready in code. It will open when Firebase is configured.',
      googlePrompt: 'Sign in with Google to read random answers from people who met the same question.',
      loadAnswersError: 'Other voices open only when this answer is saved in your account.',
      loadingAnswers: 'Looking for compatible voices…',
      makePrivate: 'Make private',
      noAnswers:
        'No other answer found yet. This room will grow when more people answer the same question.',
      openError: 'I could not open this answer to the shared room.',
      openStatus: 'Answer opened to the shared room.',
      opening: 'Opening…',
      openWithInitials: 'Share with initials',
      privateText:
        'This answer is private. You can open it to the shared room with initials only, then read voices from people who answered the same question.',
      privateError: 'I could not make this answer private.',
      privateStatus: 'Answer closed again. It stays only in your personal archive.',
      report: 'Report',
      reportError: 'The report did not arrive. I still hid this voice here.',
      title: 'Voices from others',
    },
  },
  uk: {
    archive: {
      emptyBody: 'Дай відповідь на запитання дня на головній. Відтоді цей простір почне пам’ятати.',
      emptyTitle: 'Ще немає маски',
      headerKicker: 'Архів',
      headerText: 'Твої відповіді залишаються твоїми. Дзеркала відкриваються, коли час зробив свою роботу.',
      headerTitle: 'Твоя приватна пам’ять',
      loading: 'Шукаю збережені сліди…',
      mapBadge: (count: number) => (count === 1 ? '1 слід' : `${count} слідів`),
      mapDominant: 'Найчастіша маска',
      mapDominantMany: (count: number) =>
        `Вона з’являлася ${count} разів: можливо, це межа, якої ти торкаєшся найчастіше.`,
      mapDominantOnce:
        'Поки що вона з’явилася один раз. Ще кілька відповідей допоможуть побачити форму.',
      mapNext: 'Наступне дзеркало',
      mapTitle: 'Особиста мапа',
      nextMirrorEmpty: 'Усі збережені дзеркала відкриті. Наступне народиться із сьогоднішнього запитання.',
      nextMirrorIn: (time: string) => `Відкриється через ${time}.`,
      opened: 'Відкрита',
      reflection: 'Відображення',
      reflectionOpensIn: (time: string) => `Дзеркало відкриється через ${time}.`,
      sealed: 'Запечатана',
      statsAnswers: 'відповідей',
      statsOpen: 'відкритих дзеркал',
      statsWaiting: 'очікують',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Темна',
      home: 'Головна',
      light: 'Світла',
      mask: 'Маска',
      ready: 'Готово',
      theme: 'Вигляд',
      waiting: 'Потрібно підключити',
    },
    home: {
      answerPlaceholder: 'Зніми першу маску тут…',
      cardKicker: 'Запитання дня',
      headerKicker: 'Щоденний ритуал',
      headerText: 'Пиши без ролі. Завтра відповідь повернеться лагіднішим дзеркалом.',
      loading: 'Відкриваю сьогоднішню печатку…',
      memoryBadge: 'триває',
      memoryLatest: 'Остання зустрінута маска',
      memoryReturn: 'Кожне повернення робить ритуал менш випадковим і більш твоїм.',
      memoryTitle: 'Нитка',
      open: 'Відкрита',
      promise: 'Одне запитання. Потім тиша.',
      ritualStep1: 'Одне запитання, вибране на сьогодні.',
      ritualStep2: 'Двадцять чотири години відстані.',
      ritualStep3: 'Дзеркало, яке можна перечитати без поспіху.',
      ritualTitle: 'Ритуал',
      remoteConnected: 'Архів підключено до твого акаунта Google.',
      remoteLoadError: 'Не вдалося прочитати віддалений архів.',
      remoteSaveError: 'Відповідь збережено на цьому пристрої. Віддалене збереження не вдалося.',
      reflectionWaiting: (time: string | null) =>
        `Відображення відкриється через ${time ?? 'трохи часу'}. Ця затримка є частиною ритуалу: вона дає відповіді час змінити температуру.`,
      save: 'Запечатати відповідь',
      savedPrivate: 'Відповідь збережено у твоєму особистому просторі.',
      savedShared: 'Відповідь збережено й відкрито для спільної кімнати з твоїми ініціалами.',
      savedLocal: 'Відповідь збережено на цьому пристрої.',
      sealed: 'Запечатана',
      sealedTitle: 'Відповідь запечатана',
      shareGoogle: 'Щоб відкрити відповідь для спільної кімнати, потрібен вхід Google.',
      shareText:
        'Увімкни лише якщо хочеш: інші побачать тільки ініціали і лише після відповіді на те саме запитання.',
      shareTitle: 'Захищений обмін',
      shortHint: 'Не треба писати красиво. Треба писати чесно, навіть трохи.',
      signalOne: '1 запитання',
      signalTime: '24 години',
      traces: 'сліди',
      mirrors: 'дзеркала',
      yesterdayMirror: 'Вчорашнє дзеркало',
    },
    paths: {
      featuredBody: 'Обмеження тут не трюк: воно зменшує шум, підсилює повернення і дає відповіді простір.',
      featuredKicker: 'Керований досвід',
      featuredTitle: 'Одне запитання за раз',
      headerKicker: 'Шляхи',
      headerText: 'Кожна маска має ритм: любов, страх, амбіція, самотність, сенс.',
      headerTitle: 'Обери правильні двері',
      locked: 'Ця маска ще за дверима. Вона відкриється, коли в архіві буде достатньо слідів.',
      moreQuestions: (count: number) => `Ще ${count} запитань залишаються у шляху.`,
      openQuestions: (count: number) => `${count} запитань`,
      presto: 'Незабаром',
      questionIntro:
        'Запитання, які цей шлях тримає в щоденному ритуалі. Вони не приходять усі разом: очікування є частиною досвіду.',
      selected: 'В дослідженні',
    },
    profile: {
      account: 'Акаунт',
      accountLinked: 'Підключено до Google',
      accountNotLinked: 'Не підключено',
      cloudMissing: 'Хмару не налаштовано',
      cloudMissingText: 'Відповіді залишаються на цьому пристрої, доки Firebase не буде підключено.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      headerKicker: 'Профіль',
      headerText: 'Акаунт, збереження і поширення розділені: обирай, що відкрити, а що залишити своїм.',
      headerTitle: 'Контроль, не оголення',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Стеж за проєктом поза щоденним ритуалом: оновлення, залаштунки та нові відкриття.',
      language: 'Мова',
      login: 'Увійти через Google',
      loginOpening: 'Відкриваю Google…',
      logout: 'Вийти',
      privacy: 'Приватність',
      privacyArchive: 'Особистий архів',
      privacyArchiveText: 'Збережені відповіді залишаються у твоєму просторі. Спільна кімната має окрему копію.',
      privacyConsent: 'Зворотна згода',
      privacyConsentText: 'Кожну спільну відповідь можна знову зробити приватною в Архіві.',
      privacyInitials: 'Лише ініціали',
      privacyInitialsText: 'Спільні голоси не показують повне ім’я, email або профіль Google.',
      signInText: 'Увійди, щоб повернути архів і керувати спільними відповідями.',
      status: 'Стан',
      themeHelp: 'Обери режим, який читається найкраще для тебе.',
    },
    shared: {
      firebaseMissing: 'Спільна кімната готова в коді. Вона відкриється, коли Firebase буде налаштовано.',
      googlePrompt: 'Увійди через Google, щоб читати випадкові відповіді людей із тим самим запитанням.',
      loadAnswersError:
        'Інші голоси відкриваються лише тоді, коли ця відповідь збережена у твоєму акаунті.',
      loadingAnswers: 'Шукаю сумісні голоси…',
      makePrivate: 'Зробити приватною',
      noAnswers:
        'Поки що немає іншої відповіді. Ця кімната зростатиме, коли інші люди відповідатимуть на те саме запитання.',
      openError: 'Не вдалося відкрити цю відповідь для спільної кімнати.',
      openStatus: 'Відповідь відкрито для спільної кімнати.',
      opening: 'Відкриваю…',
      openWithInitials: 'Поділитися з ініціалами',
      privateText:
        'Ця відповідь приватна. Можна відкрити її для спільної кімнати лише з ініціалами, а потім читати голоси тих, хто відповів на те саме запитання.',
      privateError: 'Не вдалося зробити цю відповідь приватною.',
      privateStatus: 'Відповідь знову закрито. Вона залишається лише у твоєму особистому архіві.',
      report: 'Поскаржитися',
      reportError: 'Скарга не надійшла. Я все одно приховав цей голос тут.',
      title: 'Голоси інших',
    },
  },
  ru: {
    archive: {
      emptyBody: 'Ответь на вопрос дня на главной. С этого момента это пространство начнёт помнить.',
      emptyTitle: 'Пока нет маски',
      headerKicker: 'Архив',
      headerText: 'Твои ответы остаются твоими. Зеркала открываются, когда время сделало свою работу.',
      headerTitle: 'Твоя личная память',
      loading: 'Ищу сохранённые следы…',
      mapBadge: (count: number) => (count === 1 ? '1 след' : `${count} следов`),
      mapDominant: 'Самая частая маска',
      mapDominantMany: (count: number) =>
        `Она появлялась ${count} раз: возможно, это порог, которого ты касаешься чаще всего.`,
      mapDominantOnce:
        'Пока она появилась один раз. Ещё несколько ответов помогут увидеть форму.',
      mapNext: 'Следующее зеркало',
      mapTitle: 'Личная карта',
      nextMirrorEmpty: 'Все сохранённые зеркала открыты. Следующее начнётся с сегодняшнего вопроса.',
      nextMirrorIn: (time: string) => `Откроется через ${time}.`,
      opened: 'Открыта',
      reflection: 'Отражение',
      reflectionOpensIn: (time: string) => `Зеркало откроется через ${time}.`,
      sealed: 'Запечатана',
      statsAnswers: 'ответов',
      statsOpen: 'открытых зеркал',
      statsWaiting: 'в ожидании',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Тёмная',
      home: 'Главная',
      light: 'Светлая',
      mask: 'Маска',
      ready: 'Готово',
      theme: 'Вид',
      waiting: 'Подключить',
    },
    home: {
      answerPlaceholder: 'Сними первую маску здесь…',
      cardKicker: 'Вопрос дня',
      headerKicker: 'Ежедневный ритуал',
      headerText: 'Пиши без роли. Завтра ответ вернётся более мягким зеркалом.',
      loading: 'Открываю сегодняшнюю печать…',
      memoryBadge: 'в процессе',
      memoryLatest: 'Последняя встреченная маска',
      memoryReturn: 'Каждое возвращение делает ритуал менее случайным и более твоим.',
      memoryTitle: 'Нить',
      open: 'Открыта',
      promise: 'Один вопрос. Потом тишина.',
      ritualStep1: 'Один вопрос, выбранный на сегодня.',
      ritualStep2: 'Двадцать четыре часа расстояния.',
      ritualStep3: 'Зеркало, которое можно перечитать без спешки.',
      ritualTitle: 'Ритуал',
      remoteConnected: 'Архив подключён к твоему аккаунту Google.',
      remoteLoadError: 'Не удалось прочитать удалённый архив.',
      remoteSaveError: 'Ответ сохранён на этом устройстве. Удалённое сохранение не удалось.',
      reflectionWaiting: (time: string | null) =>
        `Отражение откроется через ${time ?? 'немного времени'}. Эта задержка — часть ритуала: она даёт ответу время изменить температуру.`,
      save: 'Запечатать ответ',
      savedPrivate: 'Ответ сохранён в твоём личном пространстве.',
      savedShared: 'Ответ сохранён и открыт для общей комнаты с твоими инициалами.',
      savedLocal: 'Ответ сохранён на этом устройстве.',
      sealed: 'Запечатана',
      sealedTitle: 'Ответ запечатан',
      shareGoogle: 'Чтобы открыть ответ для общей комнаты, нужен вход через Google.',
      shareText:
        'Включай только если хочешь: другие увидят только инициалы и только после ответа на тот же вопрос.',
      shareTitle: 'Защищённый обмен',
      shortHint: 'Не нужно писать красиво. Нужно писать честно, даже немного.',
      signalOne: '1 вопрос',
      signalTime: '24 часа',
      traces: 'следы',
      mirrors: 'зеркала',
      yesterdayMirror: 'Вчерашнее зеркало',
    },
    paths: {
      featuredBody: 'Ограничение здесь не трюк: оно снижает шум, усиливает возвращение и даёт ответу место.',
      featuredKicker: 'Направленный опыт',
      featuredTitle: 'Один вопрос за раз',
      headerKicker: 'Пути',
      headerText: 'У каждой маски свой ритм: любовь, страх, амбиция, одиночество, смысл.',
      headerTitle: 'Выбери правильную дверь',
      locked: 'Эта маска пока за дверью. Она откроется, когда в архиве будет достаточно следов.',
      moreQuestions: (count: number) => `Ещё ${count} вопросов остаются в пути.`,
      openQuestions: (count: number) => `${count} вопросов`,
      presto: 'Скоро',
      questionIntro:
        'Вопросы, которые этот путь хранит в ежедневном ритуале. Они не приходят все сразу: ожидание — часть опыта.',
      selected: 'В исследовании',
    },
    profile: {
      account: 'Аккаунт',
      accountLinked: 'Подключено к Google',
      accountNotLinked: 'Не подключено',
      cloudMissing: 'Облако не настроено',
      cloudMissingText: 'Ответы остаются на этом устройстве, пока Firebase не подключён.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      headerKicker: 'Профиль',
      headerText: 'Аккаунт, сохранение и обмен разделены: выбирай, что открыть, а что оставить своим.',
      headerTitle: 'Контроль, не раскрытие',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Следи за проектом вне ежедневного ритуала: обновления, закулисье и новые открытия.',
      language: 'Язык',
      login: 'Войти через Google',
      loginOpening: 'Открываю Google…',
      logout: 'Выйти',
      privacy: 'Приватность',
      privacyArchive: 'Личный архив',
      privacyArchiveText: 'Сохранённые ответы остаются в твоём пространстве. Общая комната использует отдельную копию.',
      privacyConsent: 'Обратимое согласие',
      privacyConsentText: 'Любой общий ответ можно снова сделать приватным в Архиве.',
      privacyInitials: 'Только инициалы',
      privacyInitialsText: 'Общие голоса не показывают полное имя, email или профиль Google.',
      signInText: 'Войди, чтобы вернуть архив и управлять общими ответами.',
      status: 'Статус',
      themeHelp: 'Выбери режим, который читается лучше всего.',
    },
    shared: {
      firebaseMissing: 'Общая комната готова в коде. Она откроется, когда Firebase будет настроен.',
      googlePrompt: 'Войди через Google, чтобы читать случайные ответы людей с тем же вопросом.',
      loadAnswersError: 'Другие голоса открываются только когда этот ответ сохранён в твоём аккаунте.',
      loadingAnswers: 'Ищу совместимые голоса…',
      makePrivate: 'Сделать приватным',
      noAnswers:
        'Пока нет другого ответа. Эта комната будет расти, когда другие люди ответят на тот же вопрос.',
      openError: 'Не удалось открыть этот ответ для общей комнаты.',
      openStatus: 'Ответ открыт для общей комнаты.',
      opening: 'Открываю…',
      openWithInitials: 'Поделиться с инициалами',
      privateText:
        'Этот ответ приватный. Можно открыть его для общей комнаты только с инициалами, а затем читать голоса тех, кто ответил на тот же вопрос.',
      privateError: 'Не удалось сделать этот ответ приватным.',
      privateStatus: 'Ответ снова закрыт. Он остаётся только в твоём личном архиве.',
      report: 'Пожаловаться',
      reportError: 'Жалоба не отправилась. Я всё равно скрыл этот голос здесь.',
      title: 'Голоса других',
    },
  },
  es: {
    archive: {
      emptyBody: 'Responde a la pregunta del día en Inicio. Desde ahí, este espacio empezará a recordar.',
      emptyTitle: 'Aún no hay máscara',
      headerKicker: 'Archivo',
      headerText: 'Tus respuestas siguen siendo tuyas. Los espejos se abren cuando el tiempo hizo su trabajo.',
      headerTitle: 'Tu memoria privada',
      loading: 'Buscando las huellas guardadas…',
      mapBadge: (count: number) => (count === 1 ? '1 huella' : `${count} huellas`),
      mapDominant: 'Máscara más presente',
      mapDominantMany: (count: number) =>
        `Apareció ${count} veces: podría ser el umbral que más estás rozando.`,
      mapDominantOnce:
        'Por ahora apareció una vez. Hace falta alguna respuesta más para ver una forma.',
      mapNext: 'Próximo espejo',
      mapTitle: 'Mapa personal',
      nextMirrorEmpty: 'Todos los espejos guardados están abiertos. El próximo nace de la pregunta de hoy.',
      nextMirrorIn: (time: string) => `Se abre en ${time}.`,
      opened: 'Abierta',
      reflection: 'Reflexión',
      reflectionOpensIn: (time: string) => `El espejo se abre en ${time}.`,
      sealed: 'Sellada',
      statsAnswers: 'respuestas',
      statsOpen: 'espejos abiertos',
      statsWaiting: 'en espera',
    },
    common: {
      appName: 'Via la Maschera',
      dark: 'Oscuro',
      home: 'Inicio',
      light: 'Claro',
      mask: 'Máscara',
      ready: 'Listo',
      theme: 'Apariencia',
      waiting: 'Por conectar',
    },
    home: {
      answerPlaceholder: 'Quita la primera máscara aquí…',
      cardKicker: 'Pregunta de hoy',
      headerKicker: 'Ritual diario',
      headerText: 'Escribe sin actuar. Mañana la respuesta vuelve como un espejo más amable.',
      loading: 'Abriendo el sello de hoy…',
      memoryBadge: 'en curso',
      memoryLatest: 'Última máscara encontrada',
      memoryReturn: 'Cada regreso hace que el ritual sea menos casual y más tuyo.',
      memoryTitle: 'El hilo',
      open: 'Abierta',
      promise: 'Una pregunta. Luego silencio.',
      ritualStep1: 'Una sola pregunta, elegida para hoy.',
      ritualStep2: 'Veinticuatro horas de distancia.',
      ritualStep3: 'Un espejo para releer sin prisa.',
      ritualTitle: 'El ritual',
      remoteConnected: 'Archivo conectado a tu cuenta de Google.',
      remoteLoadError: 'No pude leer el archivo remoto.',
      remoteSaveError: 'Respuesta guardada en este dispositivo. El guardado remoto no funcionó.',
      reflectionWaiting: (time: string | null) =>
        `La reflexión se abre en ${time ?? 'un momento'}. Esta espera es parte del ritual: le da a la respuesta tiempo para cambiar de temperatura.`,
      save: 'Sellar la respuesta',
      savedPrivate: 'Respuesta guardada en tu espacio personal.',
      savedShared: 'Respuesta guardada y abierta a la sala compartida con tus iniciales.',
      savedLocal: 'Respuesta guardada en este dispositivo.',
      sealed: 'Sellada',
      sealedTitle: 'Respuesta sellada',
      shareGoogle: 'Para abrir esta respuesta a la sala compartida hace falta acceder con Google.',
      shareText:
        'Actívalo solo si quieres: los demás verán solo iniciales y solo después de responder a la misma pregunta.',
      shareTitle: 'Compartir protegido',
      shortHint: 'No hace falta escribir bien. Hace falta escribir de verdad, aunque sea poco.',
      signalOne: '1 pregunta',
      signalTime: '24 horas',
      traces: 'huellas',
      mirrors: 'espejos',
      yesterdayMirror: 'El espejo de ayer',
    },
    paths: {
      featuredBody: 'La escasez aquí no es truco: reduce ruido, aumenta el regreso y deja espacio a la respuesta.',
      featuredKicker: 'Experiencia guiada',
      featuredTitle: 'Una pregunta a la vez',
      headerKicker: 'Recorridos',
      headerText: 'Cada máscara tiene un ritmo: amor, miedo, ambición, soledad, sentido.',
      headerTitle: 'Elige la puerta correcta',
      locked: 'Esta máscara todavía está detrás de la puerta. Se abrirá cuando tu archivo tenga suficientes huellas.',
      moreQuestions: (count: number) => `Quedan ${count} preguntas más en el recorrido.`,
      openQuestions: (count: number) => `${count} preguntas`,
      presto: 'Pronto',
      questionIntro:
        'Preguntas que este recorrido guarda en el ritual diario. No llegan todas juntas: la espera es parte de la experiencia.',
      selected: 'En exploración',
    },
    profile: {
      account: 'Cuenta',
      accountLinked: 'Conectado a Google',
      accountNotLinked: 'No conectado',
      cloudMissing: 'Cloud no configurado',
      cloudMissingText: 'Las respuestas quedan en este dispositivo hasta que Firebase esté conectado.',
      firebase: 'Firebase',
      googleLogin: 'Google Login',
      headerKicker: 'Perfil',
      headerText: 'Cuenta, guardado y compartir quedan separados: eliges qué abrir y qué conservar tuyo.',
      headerTitle: 'Control, no exposición',
      instagram: 'Instagram',
      instagramAction: '@via_lamaschera',
      instagramText:
        'Sigue el proyecto fuera del ritual diario: novedades, detrás de escena y nuevas aperturas.',
      language: 'Idioma',
      login: 'Entrar con Google',
      loginOpening: 'Abriendo Google…',
      logout: 'Salir',
      privacy: 'Privacidad',
      privacyArchive: 'Archivo personal',
      privacyArchiveText: 'Las respuestas guardadas quedan en tu espacio. La sala compartida usa una copia separada.',
      privacyConsent: 'Consentimiento reversible',
      privacyConsentText: 'Cada respuesta compartida puede volver a ser privada desde el Archivo.',
      privacyInitials: 'Solo iniciales',
      privacyInitialsText: 'Las voces compartidas no muestran nombre completo, email ni perfil de Google.',
      signInText: 'Entra para recuperar tu archivo y gestionar las respuestas compartidas.',
      status: 'Estado',
      themeHelp: 'Elige el modo que te resulte más legible.',
    },
    shared: {
      firebaseMissing: 'La sala compartida está lista en el código. Se abrirá cuando Firebase esté configurado.',
      googlePrompt: 'Entra con Google para leer respuestas aleatorias de quien encontró la misma pregunta.',
      loadAnswersError: 'Las otras voces se abren solo cuando esta respuesta está guardada en tu cuenta.',
      loadingAnswers: 'Buscando voces compatibles…',
      makePrivate: 'Hacer privada',
      noAnswers:
        'Todavía no hay otra respuesta. Esta sala crecerá cuando otras personas respondan a la misma pregunta.',
      openError: 'No pude abrir esta respuesta a la sala compartida.',
      openStatus: 'Respuesta abierta a la sala compartida.',
      opening: 'Abriendo…',
      openWithInitials: 'Compartir con iniciales',
      privateText:
        'Esta respuesta es privada. Puedes abrirla a la sala compartida solo con iniciales y luego leer voces de quien respondió a la misma pregunta.',
      privateError: 'No pude hacer privada esta respuesta.',
      privateStatus: 'Respuesta cerrada de nuevo. Queda solo en tu archivo personal.',
      report: 'Denunciar',
      reportError: 'La denuncia no llegó. De todos modos oculté esta voz aquí.',
      title: 'Voces de otros',
    },
  },
} as const;

export type AppCopy = (typeof appCopy)[AppLanguageCode];
